export const STOP_GAME = 'STOP_GAME'
export const START_GAME = 'START_GAME'
export const OPEN_CELL = 'OPEN_CELL'
export const OPEN_MANY_CELLS = 'OPEN_MANY_CELLS'
export const SET_MANY_CELLS_OPEN = 'SET_MANY_CELLS_OPEN'
export const TOGGLE_AS_BOMB = 'TOGGLE_AS_BOMB'
